# Generated by Django 4.2.3 on 2023-07-13 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_bloguser_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogUser',
        ),
    ]
