# Generated by Django 4.2.3 on 2023-07-14 20:18

import django.core.validators
from django.db import migrations, models
import django_blogging_app.apps.user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), django_blogging_app.apps.user_profile.models.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), django_blogging_app.apps.user_profile.models.validate_only_letters]),
        ),
    ]
