# Generated by Django 4.2.3 on 2023-07-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_bloguser_first_name_alter_bloguser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='groups',
        ),
    ]
