# Generated by Django 4.2.3 on 2023-07-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_profile', '0010_remove_bloguser_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
    ]
