# Generated by Django 4.2.3 on 2023-07-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_on']},
        ),
    ]
