# Generated by Django 4.2.3 on 2023-07-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('article', '0006_article_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, to='category.category'),
        ),
    ]
