# Generated by Django 4.2.3 on 2023-07-26 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_articlerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerating',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
