# Generated by Django 4.2.3 on 2023-07-26 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_alter_articlerating_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleRating',
        ),
    ]
