# Generated by Django 4.2.3 on 2023-07-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='articles',
        ),
    ]
