# Generated by Django 4.2.3 on 2023-07-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='rating_value',
        ),
    ]
